apiVersion: 1

datasources:
  - name: ClickHouse
    uid: ClickHouse
    type: vertamedia-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    isDefault: false
    jsonData:
      defaultDatabase: analytics
      port: 8123
      server: clickhouse
      username: default
      secure: false
      timeout: 60
      addCorsHeader: false
    editable: true

